### ISSUE TITLE
bug: call of setState() before component mount

### ISSUE THREAD

**Issue by EmrysMyrddin** [alakarteio/k-mobx-react#9]
The injector calls the `toRun` function in its constructor while the component is not yet mounted or mounting.

**Comment by fabienjuif** [comment]
Nice catch, I let you open a PR.
You are a collaborator on this repo, you don't need to use your fork anymore ;)
And this is better to not use your fork because coveralls will trigger nicely

**Comment by fabienjuif** [comment]
Linked to #11
